author: Andrew Gunn

gravatarUrl: https://s.gravatar.com/avatar/fb5ba768e87a4cb19517ca1b4a4251ac

gitHubUsername:  andrewgunn
linkedInUsername:  andrewgunnrazor
twitterUsername: andrewgunn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
